# Pre-commit hooks for documentation quality
# Install with: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.13
        args: [--line-length=88]

  # Python import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile=black]

  # Python docstring formatting
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        args: [
          --in-place,
          --wrap-summaries=88,
          --wrap-descriptions=88,
          --blank,
          --style=google
        ]

  # Python docstring style checking
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: [--convention=google]
        exclude: ^(tests/|docs/|scripts/)
        additional_dependencies: [toml]

  # Python type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --no-strict-optional]
        additional_dependencies: [
          types-redis,
          types-PyYAML,
          types-requests,
          pydantic
        ]
        exclude: ^(tests/|docs/)

  # YAML validation
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        exclude: mkdocs.yml  # MkDocs uses special tags
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-merge-conflict
      - id: check-toml
      - id: mixed-line-ending
        args: [--fix=lf]

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: [--fix]
        exclude: ^(site/|.github/)

  # Documentation validation (custom hook)
  # - repo: local
  #   hooks:
  #     - id: validate-docs
  #       name: Validate Documentation Coverage
  #       entry: python scripts/validate_docs.py
  #       language: system
  #       pass_filenames: false
  #       always_run: true
  #
  #     - id: mkdocs-build
  #       name: Test MkDocs Build
  #       entry: bash -c 'mkdocs build --strict --quiet'
  #       language: system
  #       pass_filenames: false
  #       files: ^(docs/|mkdocs.yml|src/.*\.py)$
