version: '3.8'

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: eol-redis-test
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight
    environment:
      - REDIS_ARGS=--save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - eol-test

networks:
  eol-test:
    driver: bridge

volumes:
  redis-data:
    driver: local