site_name: EOL RAG Context
site_description: Intelligent RAG-based context management MCP server for the EOL Framework
site_url: https://eoln.github.io/eol/packages/eol-rag-context/
repo_url: https://github.com/eoln/eol
repo_name: eoln/eol
edit_uri: edit/main/packages/eol-rag-context/docs/

# Configuration
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.ico
  logo: assets/logo.svg

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - mike:  # Uncomment when mike is installed for versioning
  #     canonical_version: latest
  - mkdocstrings:
      handlers:
        python:
          options:
            # Docstring parsing options
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            # API documentation options
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            show_object_full_path: false
            show_category_heading: true
            # Type annotations
            show_signature_annotations: true
            # Rendering options
            heading_level: 2
            members_order: source
            group_by_category: true
            show_submodules: false
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: eoln
      repo: eol
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - getting-started/index.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - First Steps: getting-started/first-steps.md
  - User Guide:
    - user-guide/index.md
    - Document Indexing: user-guide/indexing.md
    - Search & Retrieval: user-guide/searching.md
    - Advanced Features: user-guide/advanced-features.md
    - MCP Integration: user-guide/integrations.md
  - API Reference:
    - api-reference/index.md
    - Server: api-reference/server.md
    - Configuration: api-reference/config.md
    - Indexer: api-reference/indexer.md
    - Embeddings: api-reference/embeddings.md
    - Redis Client: api-reference/redis-client.md
    - Semantic Cache: api-reference/semantic-cache.md
    - Knowledge Graph: api-reference/knowledge-graph.md
    - File Watcher: api-reference/file-watcher.md
    - Document Processor: api-reference/document-processor.md
  - Examples:
    - examples/index.md
    - Basic Usage: examples/basic-usage.md
    - Advanced Usage: examples/advanced-usage.md
    - Integration Examples: examples/integration-examples.md
    - Troubleshooting: examples/troubleshooting.md
  - Development:
    - development/index.md
    - Contributing: development/contributing.md
    - Architecture: development/architecture.md
    - Testing: development/testing.md
    - Deployment: development/deployment.md

# Extra
extra:
  # version:  # Uncomment when mike is installed
  #   provider: mike
  #   default: latest
  #   alias: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eoln/eol
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/eol-rag-context/
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

# Additional files
extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Copyright
copyright: Copyright &copy; 2025 EOLN.EU