[project]
name = "eol-core"
version = "0.1.0"
description = "Core engine for EOL framework"
requires-python = ">=3.11"
license = { text = "GPL-3.0" }
authors = [
    { name = "eoln", email = "eoln@users.noreply.github.com" }
]
dependencies = [
    "pyyaml>=6.0",
    "markdown>=3.5",
    "pydantic>=2.0",
    "networkx>=3.0",
    "aiofiles>=23.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"