[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "eol-core"
version = "0.1.0"
description = "Core engine for the EOL AI Framework"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "GPL-3.0" }
authors = [
    { name = "EOLN.EU", email = "dev@eoln.eu" }
]

# Core dependencies
dependencies = [
    "pydantic>=2.0.0",
    "pydantic-settings>=2.0.0",
    "typer>=0.9.0",
    "rich>=13.0.0",
    "pyyaml>=6.0",
    "aiofiles>=23.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "black>=24.0.0",
    "ruff>=0.1.0",
    "mypy>=1.5.0",
]

[project.urls]
Homepage = "https://github.com/eoln/eol"
Repository = "https://github.com/eoln/eol"

[tool.hatch.build.targets.wheel]
packages = ["src/eol"]

# UV Package Configuration
[tool.uv]
workspace = true

[tool.uv.sources]
# Workspace dependencies
eol-rag-context = { workspace = true }